In [1]:
# MULTI-CLASS CLASSIFICATION FINAL IMPLEMENTATION


# Import Libraries
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from sklearn.multiclass import OneVsRestClassifier, OneVsOneClassifier

from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

# 1. Load Dataset

data = load_iris()
X = data.data
y = data.target

print("Dataset Shape:", X.shape)

# 2. Train-Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 3. Feature Scaling

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 4. MODELS IMPLEMENTATION


results = []

# (A) Logistic Regression - One vs Rest

ovr_lr = OneVsRestClassifier(LogisticRegression(max_iter=200))
ovr_lr.fit(X_train, y_train)

y_pred_ovr_lr = ovr_lr.predict(X_test)

acc_ovr_lr = accuracy_score(y_test, y_pred_ovr_lr)
f1_ovr_lr = f1_score(y_test, y_pred_ovr_lr, average='weighted')

results.append(["OvR - Logistic Regression", acc_ovr_lr, f1_ovr_lr])


# (B) Logistic Regression - One vs One

ovo_lr = OneVsOneClassifier(LogisticRegression(max_iter=200))
ovo_lr.fit(X_train, y_train)

y_pred_ovo_lr = ovo_lr.predict(X_test)

acc_ovo_lr = accuracy_score(y_test, y_pred_ovo_lr)
f1_ovo_lr = f1_score(y_test, y_pred_ovo_lr, average='weighted')

results.append(["OvO - Logistic Regression", acc_ovo_lr, f1_ovo_lr])


# (C) SVM - One vs Rest

ovr_svm = OneVsRestClassifier(SVC(kernel='linear'))
ovr_svm.fit(X_train, y_train)

y_pred_ovr_svm = ovr_svm.predict(X_test)

acc_ovr_svm = accuracy_score(y_test, y_pred_ovr_svm)
f1_ovr_svm = f1_score(y_test, y_pred_ovr_svm, average='weighted')

results.append(["OvR - SVM", acc_ovr_svm, f1_ovr_svm])

# (D) SVM - One vs One

ovo_svm = OneVsOneClassifier(SVC(kernel='linear'))
ovo_svm.fit(X_train, y_train)

y_pred_ovo_svm = ovo_svm.predict(X_test)

acc_ovo_svm = accuracy_score(y_test, y_pred_ovo_svm)
f1_ovo_svm = f1_score(y_test, y_pred_ovo_svm, average='weighted')

results.append(["OvO - SVM", acc_ovo_svm, f1_ovo_svm])

# 5. Results Comparison Table

results_df = pd.DataFrame(results, columns=["Model", "Accuracy", "F1 Score"])

print("\n================ FINAL RESULTS ================\n")
print(results_df)


# 6. Detailed Evaluation (Example: Best Model)


# Choose best model (based on F1 Score)
best_model_name = results_df.sort_values(by="F1 Score", ascending=False).iloc[0]["Model"]

print("\nBest Model:", best_model_name)

# Using OvO SVM as example for detailed metrics
print("\nClassification Report (OvO SVM):\n")
print(classification_report(y_test, y_pred_ovo_svm))

print("\nConfusion Matrix (OvO SVM):\n")
print(confusion_matrix(y_test, y_pred_ovo_svm))

Dataset Shape: (150, 4)

================ FINAL RESULTS ================

                       Model  Accuracy  F1 Score
0  OvR - Logistic Regression  0.900000  0.899749
1  OvO - Logistic Regression  0.966667  0.966583
2                  OvR - SVM  0.900000  0.899749
3                  OvO - SVM  1.000000  1.000000

Best Model: OvO - SVM

Classification Report (OvO SVM):

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Confusion Matrix (OvO SVM):

[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
